### PR TITLE
Compat with latest nightly

### PR DESCRIPTION
**Pull request by kivikakk**
Building against `rustc 1.14.0-nightly (098d22845 2016-10-13)`.

### CODE REVIEW

**Comment by kivikakk** [comment]
Looking into the test failures; it may be more complicated than this simple fix!

**Comment by kivikakk** [comment]
Looks like this is probably `#![allow(match_of_unit_variant_via_paren_dotdot)]` going away. I'll see if I can fix!

**Comment by goffrie** [comment]
Thanks! Yeah, I was thinking of how to solve that issue. Probably the best way is to forbid matching tuple-variants with just `Token` and force using `Token(..)`; then we can infer the tuple-ness of a variant.

**Comment by kivikakk** [comment]
D'you mean accepting something like this?

``` rust
        assign: Expr {
            Print(..) assign[a] => Expr {
                  ^
```

And then generating a plain `Print` pattern to match instead? I'll try to work up a spike for this 👍

**Comment by goffrie** [comment]
I actually mean the opposite. Right now the `Print` variant can only be matched as `Print`, and that's fine. But e.g. `Ident(String)` can be matched as both `Ident(s)` and just plain `Ident` (which discards the contents). That means that, for a nonterminal that's matched in the latter form, we can't tell whether to generate a unit-like pattern or a tuple-like pattern. But if we forbid plain `Ident` then we'll have enough information to infer it.

**Comment by kivikakk** [comment]
Ahh, understood! I'll see if I can get anything like that working, then. :)

**Pull request merged**
